services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        NODE_VERSION: "22.11.0"
        YARN_VERSION: "1.22.19"
        MB_EDITION: "oss"
        VERSION: "v0.0.1-radar"
        # Optional: pass proxies to the builder if your network requires them
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    image: metabase-radar
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db
    volumes:
      - ./metabase.db:/metabase.db
    restart: unless-stopped
